[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "roms_nc"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "xarray[complete] == 2023.7.0",
    "ipykernel",
]

[tool.setuptools.packages.find]
include = ["roms_nc"]
